// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiclientgo

import (
	"github.com/gleanwork/api-client-go/internal/config"
	"github.com/gleanwork/api-client-go/internal/hooks"
)

type Client struct {
	Activity       *Activity
	Announcements  *Announcements
	Answers        *Answers
	Authentication *ClientAuthentication
	Chat           *ClientChat
	Agents         *ClientAgents
	Collections    *Collections
	Documents      *ClientDocuments
	Insights       *Insights
	Messages       *Messages
	Pins           *Pins
	Search         *ClientSearch
	Entities       *Entities
	Shortcuts      *ClientShortcuts
	Verification   *Verification
	Tools          *Tools
	Governance     *Governance
	Datasources    *ClientDatasources

	rootSDK          *Glean
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newClient(rootSDK *Glean, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Client {
	return &Client{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		Activity:         newActivity(rootSDK, sdkConfig, hooks),
		Announcements:    newAnnouncements(rootSDK, sdkConfig, hooks),
		Answers:          newAnswers(rootSDK, sdkConfig, hooks),
		Authentication:   newClientAuthentication(rootSDK, sdkConfig, hooks),
		Chat:             newClientChat(rootSDK, sdkConfig, hooks),
		Agents:           newClientAgents(rootSDK, sdkConfig, hooks),
		Collections:      newCollections(rootSDK, sdkConfig, hooks),
		Documents:        newClientDocuments(rootSDK, sdkConfig, hooks),
		Insights:         newInsights(rootSDK, sdkConfig, hooks),
		Messages:         newMessages(rootSDK, sdkConfig, hooks),
		Pins:             newPins(rootSDK, sdkConfig, hooks),
		Search:           newClientSearch(rootSDK, sdkConfig, hooks),
		Entities:         newEntities(rootSDK, sdkConfig, hooks),
		Shortcuts:        newClientShortcuts(rootSDK, sdkConfig, hooks),
		Verification:     newVerification(rootSDK, sdkConfig, hooks),
		Tools:            newTools(rootSDK, sdkConfig, hooks),
		Governance:       newGovernance(rootSDK, sdkConfig, hooks),
		Datasources:      newClientDatasources(rootSDK, sdkConfig, hooks),
	}
}
