// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apiclientgo

type Client struct {
	Activity       *Activity
	Activities     *Activities
	Announcements  *Announcements
	Answers        *Answers
	Authentication *ClientAuthentication
	Chat           *Chat
	Collections    *Collections
	Documents      *ClientDocuments
	Insights       *Insights
	Messages       *Messages
	Pins           *Pins
	Search         *Search
	Entities       *Entities
	Shortcuts      *ClientShortcuts
	Summarize      *Summarize
	Verification   *Verification

	sdkConfiguration sdkConfiguration
}

func newClient(sdkConfig sdkConfiguration) *Client {
	return &Client{
		sdkConfiguration: sdkConfig,
		Activity:         newActivity(sdkConfig),
		Activities:       newActivities(sdkConfig),
		Announcements:    newAnnouncements(sdkConfig),
		Answers:          newAnswers(sdkConfig),
		Authentication:   newClientAuthentication(sdkConfig),
		Chat:             newChat(sdkConfig),
		Collections:      newCollections(sdkConfig),
		Documents:        newClientDocuments(sdkConfig),
		Insights:         newInsights(sdkConfig),
		Messages:         newMessages(sdkConfig),
		Pins:             newPins(sdkConfig),
		Search:           newSearch(sdkConfig),
		Entities:         newEntities(sdkConfig),
		Shortcuts:        newClientShortcuts(sdkConfig),
		Summarize:        newSummarize(sdkConfig),
		Verification:     newVerification(sdkConfig),
	}
}
