// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type DeletedraftannouncementRequest struct {
	// Email address of a user on whose behalf the request is intended to be made (should be non-empty only for global tokens).
	XScioActas *string `header:"style=simple,explode=false,name=X-Scio-Actas"`
	// Auth type being used to access the endpoint (should be non-empty only for global tokens).
	XGleanAuthType *string `header:"style=simple,explode=false,name=X-Glean-Auth-Type"`
	// Delete draft announcement request
	DeleteAnnouncementRequest components.DeleteAnnouncementRequest `request:"mediaType=application/json"`
}

func (o *DeletedraftannouncementRequest) GetXScioActas() *string {
	if o == nil {
		return nil
	}
	return o.XScioActas
}

func (o *DeletedraftannouncementRequest) GetXGleanAuthType() *string {
	if o == nil {
		return nil
	}
	return o.XGleanAuthType
}

func (o *DeletedraftannouncementRequest) GetDeleteAnnouncementRequest() components.DeleteAnnouncementRequest {
	if o == nil {
		return components.DeleteAnnouncementRequest{}
	}
	return o.DeleteAnnouncementRequest
}

type DeletedraftannouncementResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeletedraftannouncementResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
