// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type ExecuteactiontoolRequest struct {
	// The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
	TimezoneOffset *int64 `queryParam:"style=form,explode=true,name=timezoneOffset"`
	// Execute Action Tool request
	ExecuteActionToolRequest components.ExecuteActionToolRequest `request:"mediaType=application/json"`
}

func (o *ExecuteactiontoolRequest) GetTimezoneOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.TimezoneOffset
}

func (o *ExecuteactiontoolRequest) GetExecuteActionToolRequest() components.ExecuteActionToolRequest {
	if o == nil {
		return components.ExecuteActionToolRequest{}
	}
	return o.ExecuteActionToolRequest
}

type ExecuteactiontoolResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ExecuteActionToolResponse *components.ExecuteActionToolResponse
}

func (o *ExecuteactiontoolResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ExecuteactiontoolResponse) GetExecuteActionToolResponse() *components.ExecuteActionToolResponse {
	if o == nil {
		return nil
	}
	return o.ExecuteActionToolResponse
}
