// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type MessagesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	MessagesResponse *components.MessagesResponse
}

func (o *MessagesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *MessagesResponse) GetMessagesResponse() *components.MessagesResponse {
	if o == nil {
		return nil
	}
	return o.MessagesResponse
}
