// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type PlatformSkillsCreateVersionRequest struct {
	// Glean skill ID.
	SkillID                           string                                       `pathParam:"style=simple,explode=false,name=skill_id"`
	PlatformSkillVersionCreateRequest components.PlatformSkillVersionCreateRequest `request:"mediaType=multipart/form-data"`
}

func (p *PlatformSkillsCreateVersionRequest) GetSkillID() string {
	if p == nil {
		return ""
	}
	return p.SkillID
}

func (p *PlatformSkillsCreateVersionRequest) GetPlatformSkillVersionCreateRequest() components.PlatformSkillVersionCreateRequest {
	if p == nil {
		return components.PlatformSkillVersionCreateRequest{}
	}
	return p.PlatformSkillVersionCreateRequest
}

type PlatformSkillsCreateVersionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response.
	PlatformSkillVersionCreateResponse *components.PlatformSkillVersionCreateResponse
}

func (p *PlatformSkillsCreateVersionResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PlatformSkillsCreateVersionResponse) GetPlatformSkillVersionCreateResponse() *components.PlatformSkillVersionCreateResponse {
	if p == nil {
		return nil
	}
	return p.PlatformSkillVersionCreateResponse
}
