// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/internal/utils"
	"github.com/gleanwork/api-client-go/models/components"
	"github.com/gleanwork/api-client-go/types"
	"github.com/gleanwork/api-client-go/types/stream"
)

type PlatformSkillsPreviewSourceStreamRequest struct {
	// GitHub URL for a skill directory, SKILL.md file, or repository to inspect.
	SourceURL string `json:"source_url"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	stream_ *bool `const:"true" json:"stream"`
}

func (p PlatformSkillsPreviewSourceStreamRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkillsPreviewSourceStreamRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformSkillsPreviewSourceStreamRequest) GetSourceURL() string {
	if p == nil {
		return ""
	}
	return p.SourceURL
}

func (p *PlatformSkillsPreviewSourceStreamRequest) GetStream() *bool {
	return types.Pointer(true)
}

type PlatformSkillsPreviewSourceStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response.
	PlatformSkillSourcePreviewStreamEventServerSentEvent *stream.EventStream[components.PlatformSkillSourcePreviewStreamEventServerSentEvent]
}

func (p *PlatformSkillsPreviewSourceStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PlatformSkillsPreviewSourceStreamResponse) GetPlatformSkillSourcePreviewStreamEventServerSentEvent() *stream.EventStream[components.PlatformSkillSourcePreviewStreamEventServerSentEvent] {
	if p == nil {
		return nil
	}
	return p.PlatformSkillSourcePreviewStreamEventServerSentEvent
}
