// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type PlatformTriggersGetRequest struct {
	// ID of the trigger to retrieve.
	TriggerID string `pathParam:"style=simple,explode=false,name=trigger_id"`
}

func (p *PlatformTriggersGetRequest) GetTriggerID() string {
	if p == nil {
		return ""
	}
	return p.TriggerID
}

type PlatformTriggersGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response.
	PlatformTriggerGetResponse *components.PlatformTriggerGetResponse
}

func (p *PlatformTriggersGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PlatformTriggersGetResponse) GetPlatformTriggerGetResponse() *components.PlatformTriggerGetResponse {
	if p == nil {
		return nil
	}
	return p.PlatformTriggerGetResponse
}
