// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
	"github.com/gleanwork/api-client-go/models/components"
	"github.com/gleanwork/api-client-go/types"
	"github.com/gleanwork/api-client-go/types/stream"
)

type PlatformChatCreateStreamInputType string

const (
	PlatformChatCreateStreamInputTypeStr                             PlatformChatCreateStreamInputType = "str"
	PlatformChatCreateStreamInputTypeArrayOfPlatformChatInputMessage PlatformChatCreateStreamInputType = "arrayOfPlatformChatInputMessage"
)

// PlatformChatCreateStreamInput - Either a plain string (single user turn) or a chronological array of `USER`/`ASSISTANT` messages. The final array message must be `USER`.
type PlatformChatCreateStreamInput struct {
	Str                             *string                               `queryParam:"inline" union:"member"`
	ArrayOfPlatformChatInputMessage []components.PlatformChatInputMessage `queryParam:"inline" union:"member"`

	Type PlatformChatCreateStreamInputType
}

func CreatePlatformChatCreateStreamInputStr(str string) PlatformChatCreateStreamInput {
	typ := PlatformChatCreateStreamInputTypeStr

	return PlatformChatCreateStreamInput{
		Str:  &str,
		Type: typ,
	}
}

func CreatePlatformChatCreateStreamInputArrayOfPlatformChatInputMessage(arrayOfPlatformChatInputMessage []components.PlatformChatInputMessage) PlatformChatCreateStreamInput {
	typ := PlatformChatCreateStreamInputTypeArrayOfPlatformChatInputMessage

	return PlatformChatCreateStreamInput{
		ArrayOfPlatformChatInputMessage: arrayOfPlatformChatInputMessage,
		Type:                            typ,
	}
}

func (u *PlatformChatCreateStreamInput) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PlatformChatCreateStreamInputTypeStr,
			Value: &str,
		})
	}

	var arrayOfPlatformChatInputMessage []components.PlatformChatInputMessage = []components.PlatformChatInputMessage{}
	if err := utils.UnmarshalJSON(data, &arrayOfPlatformChatInputMessage, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PlatformChatCreateStreamInputTypeArrayOfPlatformChatInputMessage,
			Value: arrayOfPlatformChatInputMessage,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PlatformChatCreateStreamInput", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PlatformChatCreateStreamInput", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(PlatformChatCreateStreamInputType)
	switch best.Type {
	case PlatformChatCreateStreamInputTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case PlatformChatCreateStreamInputTypeArrayOfPlatformChatInputMessage:
		u.ArrayOfPlatformChatInputMessage = best.Value.([]components.PlatformChatInputMessage)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PlatformChatCreateStreamInput", string(data))
}

func (u PlatformChatCreateStreamInput) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfPlatformChatInputMessage != nil {
		return utils.MarshalJSON(u.ArrayOfPlatformChatInputMessage, "", true)
	}

	return nil, errors.New("could not marshal union type PlatformChatCreateStreamInput: all fields are null")
}

type PlatformChatCreateStreamRequest struct {
	// Either a plain string (single user turn) or a chronological array of `USER`/`ASSISTANT` messages. The final array message must be `USER`.
	//
	Input PlatformChatCreateStreamInput `json:"input"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	stream_ *bool `const:"true" json:"stream"`
	// When true (default), persist the interaction and return a `conversation_id`. When false, run ephemerally with no persistence.
	//
	Store *bool `default:"true" json:"store"`
	// Continue an existing stored conversation. Incompatible with message-array `input` and with `store: false`.
	//
	ConversationID *string `json:"conversation_id,omitempty"`
}

func (p PlatformChatCreateStreamRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformChatCreateStreamRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformChatCreateStreamRequest) GetInput() PlatformChatCreateStreamInput {
	if p == nil {
		return PlatformChatCreateStreamInput{}
	}
	return p.Input
}

func (p *PlatformChatCreateStreamRequest) GetStream() *bool {
	return types.Pointer(true)
}

func (p *PlatformChatCreateStreamRequest) GetStore() *bool {
	if p == nil {
		return nil
	}
	return p.Store
}

func (p *PlatformChatCreateStreamRequest) GetConversationID() *string {
	if p == nil {
		return nil
	}
	return p.ConversationID
}

type PlatformChatCreateStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response.
	PlatformChatStreamEventServerSentEvent *stream.EventStream[components.PlatformChatStreamEventServerSentEvent]
}

func (p *PlatformChatCreateStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PlatformChatCreateStreamResponse) GetPlatformChatStreamEventServerSentEvent() *stream.EventStream[components.PlatformChatStreamEventServerSentEvent] {
	if p == nil {
		return nil
	}
	return p.PlatformChatStreamEventServerSentEvent
}
