// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type PostAPIIndexV1DebugDatasourceDocumentRequest struct {
	// The datasource to which the document belongs
	Datasource           string                          `pathParam:"style=simple,explode=false,name=datasource"`
	DebugDocumentRequest components.DebugDocumentRequest `request:"mediaType=application/json"`
}

func (p *PostAPIIndexV1DebugDatasourceDocumentRequest) GetDatasource() string {
	if p == nil {
		return ""
	}
	return p.Datasource
}

func (p *PostAPIIndexV1DebugDatasourceDocumentRequest) GetDebugDocumentRequest() components.DebugDocumentRequest {
	if p == nil {
		return components.DebugDocumentRequest{}
	}
	return p.DebugDocumentRequest
}

// #region class-body-postapiindexv1debugdatasourcedocumentrequest
// #endregion class-body-postapiindexv1debugdatasourcedocumentrequest

type PostAPIIndexV1DebugDatasourceDocumentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DebugDocumentResponse *components.DebugDocumentResponse
}

func (p *PostAPIIndexV1DebugDatasourceDocumentResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostAPIIndexV1DebugDatasourceDocumentResponse) GetDebugDocumentResponse() *components.DebugDocumentResponse {
	if p == nil {
		return nil
	}
	return p.DebugDocumentResponse
}

// #region class-body-postapiindexv1debugdatasourcedocumentresponse
// #endregion class-body-postapiindexv1debugdatasourcedocumentresponse
