// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

var PutRestAPIIndexCustomMetadataSchemaGroupNameServerList = []string{
	"https://{instance}-be.glean.com",
}

type PutRestAPIIndexCustomMetadataSchemaGroupNameRequest struct {
	// Name of the metadata group schema
	GroupName            string                          `pathParam:"style=simple,explode=false,name=groupName"`
	CustomMetadataSchema components.CustomMetadataSchema `request:"mediaType=application/json"`
}

func (p *PutRestAPIIndexCustomMetadataSchemaGroupNameRequest) GetGroupName() string {
	if p == nil {
		return ""
	}
	return p.GroupName
}

func (p *PutRestAPIIndexCustomMetadataSchemaGroupNameRequest) GetCustomMetadataSchema() components.CustomMetadataSchema {
	if p == nil {
		return components.CustomMetadataSchema{}
	}
	return p.CustomMetadataSchema
}

type PutRestAPIIndexCustomMetadataSchemaGroupNameResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	SuccessResponse *components.SuccessResponse
}

func (p *PutRestAPIIndexCustomMetadataSchemaGroupNameResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PutRestAPIIndexCustomMetadataSchemaGroupNameResponse) GetSuccessResponse() *components.SuccessResponse {
	if p == nil {
		return nil
	}
	return p.SuccessResponse
}
