// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/gleanwork/api-client-go/models/components"
)

type RotateDatasourceCredentialsRequest struct {
	// The full datasource instance identifier (e.g. o365sharepoint_abc123)
	DatasourceInstanceID               string                                        `pathParam:"style=simple,explode=false,name=datasourceInstanceId"`
	RotateDatasourceCredentialsRequest components.RotateDatasourceCredentialsRequest `request:"mediaType=application/json"`
}

func (r *RotateDatasourceCredentialsRequest) GetDatasourceInstanceID() string {
	if r == nil {
		return ""
	}
	return r.DatasourceInstanceID
}

func (r *RotateDatasourceCredentialsRequest) GetRotateDatasourceCredentialsRequest() components.RotateDatasourceCredentialsRequest {
	if r == nil {
		return components.RotateDatasourceCredentialsRequest{}
	}
	return r.RotateDatasourceCredentialsRequest
}

type RotateDatasourceCredentialsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DatasourceCredentialStatusResponse *components.DatasourceCredentialStatusResponse
}

func (r *RotateDatasourceCredentialsResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RotateDatasourceCredentialsResponse) GetDatasourceCredentialStatusResponse() *components.DatasourceCredentialStatusResponse {
	if r == nil {
		return nil
	}
	return r.DatasourceCredentialStatusResponse
}
