// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	apiclientgo "github.com/gleanwork/api-client-go"
	"github.com/gleanwork/api-client-go/internal/utils"
	"github.com/gleanwork/api-client-go/models/components"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestClientDatasources_GetDatasourceInstanceConfiguration(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getDatasourceInstanceConfiguration")

	s := apiclientgo.New(
		apiclientgo.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		apiclientgo.WithClient(testHTTPClient),
		apiclientgo.WithSecurity(utils.GetEnv("GLEAN_API_TOKEN", "value")),
	)

	res, err := s.Client.Datasources.RetrieveConfiguration(ctx, "o365sharepoint", "o365sharepoint_abc123")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestClientDatasources_UpdateDatasourceInstanceConfiguration(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("updateDatasourceInstanceConfiguration")

	s := apiclientgo.New(
		apiclientgo.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		apiclientgo.WithClient(testHTTPClient),
		apiclientgo.WithSecurity(utils.GetEnv("GLEAN_API_TOKEN", "value")),
	)

	res, err := s.Client.Datasources.UpdateConfiguration(ctx, "o365sharepoint", "o365sharepoint_abc123", components.UpdateDatasourceConfigurationRequest{
		Configuration: components.DatasourceInstanceConfiguration{
			Values: map[string]components.ConfigurationValue{},
		},
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestClientDatasources_GetDatasourceCredentialStatus(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getDatasourceCredentialStatus")

	s := apiclientgo.New(
		apiclientgo.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		apiclientgo.WithClient(testHTTPClient),
		apiclientgo.WithSecurity(utils.GetEnv("GLEAN_API_TOKEN", "value")),
	)

	res, err := s.Client.Datasources.RetrieveCredentialStatus(ctx, "o365sharepoint_abc123")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestClientDatasources_RotateDatasourceCredentials(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("rotateDatasourceCredentials")

	s := apiclientgo.New(
		apiclientgo.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		apiclientgo.WithClient(testHTTPClient),
		apiclientgo.WithSecurity(utils.GetEnv("GLEAN_API_TOKEN", "value")),
	)

	res, err := s.Client.Datasources.RotateCredentials(ctx, "o365sharepoint_abc123", components.RotateDatasourceCredentialsRequest{
		Credentials: components.DatasourceInstanceConfiguration{
			Values: map[string]components.ConfigurationValue{
				"key": components.ConfigurationValue{},
			},
		},
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}
