// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActionAuthType - Authentication mechanism used by an action pack.
//   - `AUTH_USER_OAUTH`: Requires per-user OAuth consent to the third-party tool.
//   - `AUTH_ADMIN`: Uses a service-account / admin-owned credential. End users do not authorize individually.
//   - `AUTH_NONE`: Action pack requires no authentication.
type ActionAuthType string

const (
	ActionAuthTypeAuthUserOauth ActionAuthType = "AUTH_USER_OAUTH"
	ActionAuthTypeAuthAdmin     ActionAuthType = "AUTH_ADMIN"
	ActionAuthTypeAuthNone      ActionAuthType = "AUTH_NONE"
)

func (e ActionAuthType) ToPointer() *ActionAuthType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ActionAuthType) IsExact() bool {
	if e != nil {
		switch *e {
		case "AUTH_USER_OAUTH", "AUTH_ADMIN", "AUTH_NONE":
			return true
		}
	}
	return false
}
