// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
)

type ChatCustomEntitySourceType string

const (
	ChatCustomEntitySourceTypeCustomEntity ChatCustomEntitySourceType = "CUSTOM_ENTITY"
)

func (e ChatCustomEntitySourceType) ToPointer() *ChatCustomEntitySourceType {
	return &e
}
func (e *ChatCustomEntitySourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CUSTOM_ENTITY":
		*e = ChatCustomEntitySourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatCustomEntitySourceType: %v", v)
	}
}

type ChatCustomEntitySource struct {
	Type       ChatCustomEntitySourceType `json:"type"`
	EntityID   string                     `json:"entity_id"`
	Name       *string                    `json:"name,omitempty"`
	Title      *string                    `json:"title,omitempty"`
	URL        *string                    `json:"url,omitempty"`
	Datasource *string                    `json:"datasource,omitempty"`
}

func (c ChatCustomEntitySource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatCustomEntitySource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatCustomEntitySource) GetType() ChatCustomEntitySourceType {
	if c == nil {
		return ChatCustomEntitySourceType("")
	}
	return c.Type
}

func (c *ChatCustomEntitySource) GetEntityID() string {
	if c == nil {
		return ""
	}
	return c.EntityID
}

func (c *ChatCustomEntitySource) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *ChatCustomEntitySource) GetTitle() *string {
	if c == nil {
		return nil
	}
	return c.Title
}

func (c *ChatCustomEntitySource) GetURL() *string {
	if c == nil {
		return nil
	}
	return c.URL
}

func (c *ChatCustomEntitySource) GetDatasource() *string {
	if c == nil {
		return nil
	}
	return c.Datasource
}
