// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ChatMessageFragment - A typed fragment within a chat message that carries text or structured content such as citations, actions, and tool output.
type ChatMessageFragment struct {
	// An array of entities in the work graph retrieved via a data request.
	StructuredResults []StructuredResult `json:"structuredResults,omitempty"`
	// An opaque token that represents this particular result in this particular query. To be used for /feedback reporting.
	TrackingToken   *string          `json:"trackingToken,omitempty"`
	Text            *string          `json:"text,omitempty"`
	QuerySuggestion *QuerySuggestion `json:"querySuggestion,omitempty"`
	// Structure for file uploaded by a user for Chat.
	File   *ChatFile `json:"file,omitempty"`
	Action *ToolInfo `json:"action,omitempty"`
	// Information about the source for a ChatMessage.
	Citation          *ChatMessageCitation `json:"citation,omitempty"`
	ServerToolRequest *ServerToolRequest   `json:"serverToolRequest,omitempty"`
	// Response to a server tool request. The applicable fields depend on requestType:
	//
	// For EXECUTION requests:
	// - isGranted: whether tool execution is approved
	// - reason: optional explanation
	//
	// For AUTHENTICATION_SUGGESTION requests:
	// - isGranted: whether auth completed successfully (true=connected, false=skipped)
	// - authContext: contains serverId or actionPackId for identifying the authenticated entity
	// - reason: optional explanation for skip
	//
	// For VOTE_SUGGESTION requests:
	// - voted: whether the user voted for this tool
	//
	// For SANDBOX_EGRESS requests:
	// - isGranted: whether the sandbox egress call is approved
	//
	ServerToolResponse *ServerToolResponse `json:"serverToolResponse,omitempty"`
}

func (c *ChatMessageFragment) GetStructuredResults() []StructuredResult {
	if c == nil {
		return nil
	}
	return c.StructuredResults
}

func (c *ChatMessageFragment) GetTrackingToken() *string {
	if c == nil {
		return nil
	}
	return c.TrackingToken
}

func (c *ChatMessageFragment) GetText() *string {
	if c == nil {
		return nil
	}
	return c.Text
}

func (c *ChatMessageFragment) GetQuerySuggestion() *QuerySuggestion {
	if c == nil {
		return nil
	}
	return c.QuerySuggestion
}

func (c *ChatMessageFragment) GetFile() *ChatFile {
	if c == nil {
		return nil
	}
	return c.File
}

func (c *ChatMessageFragment) GetAction() *ToolInfo {
	if c == nil {
		return nil
	}
	return c.Action
}

func (c *ChatMessageFragment) GetCitation() *ChatMessageCitation {
	if c == nil {
		return nil
	}
	return c.Citation
}

func (c *ChatMessageFragment) GetServerToolRequest() *ServerToolRequest {
	if c == nil {
		return nil
	}
	return c.ServerToolRequest
}

func (c *ChatMessageFragment) GetServerToolResponse() *ServerToolResponse {
	if c == nil {
		return nil
	}
	return c.ServerToolResponse
}
