// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
)

type ChatPersonSourceType string

const (
	ChatPersonSourceTypePerson ChatPersonSourceType = "PERSON"
)

func (e ChatPersonSourceType) ToPointer() *ChatPersonSourceType {
	return &e
}
func (e *ChatPersonSourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PERSON":
		*e = ChatPersonSourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatPersonSourceType: %v", v)
	}
}

type ChatPersonSource struct {
	Type     ChatPersonSourceType `json:"type"`
	PersonID string               `json:"person_id"`
	Name     *string              `json:"name,omitempty"`
	URL      *string              `json:"url,omitempty"`
}

func (c ChatPersonSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatPersonSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ChatPersonSource) GetType() ChatPersonSourceType {
	if c == nil {
		return ChatPersonSourceType("")
	}
	return c.Type
}

func (c *ChatPersonSource) GetPersonID() string {
	if c == nil {
		return ""
	}
	return c.PersonID
}

func (c *ChatPersonSource) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *ChatPersonSource) GetURL() *string {
	if c == nil {
		return nil
	}
	return c.URL
}
