// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FeedResultCategory - Category of the result, one of the requested categories in incoming request.
type FeedResultCategory string

const (
	FeedResultCategoryDocumentSuggestion           FeedResultCategory = "DOCUMENT_SUGGESTION"
	FeedResultCategoryDocumentSuggestionScenario   FeedResultCategory = "DOCUMENT_SUGGESTION_SCENARIO"
	FeedResultCategoryTrendingDocument             FeedResultCategory = "TRENDING_DOCUMENT"
	FeedResultCategoryUseCase                      FeedResultCategory = "USE_CASE"
	FeedResultCategoryVerificationReminder         FeedResultCategory = "VERIFICATION_REMINDER"
	FeedResultCategoryEvent                        FeedResultCategory = "EVENT"
	FeedResultCategoryAnnouncement                 FeedResultCategory = "ANNOUNCEMENT"
	FeedResultCategoryMention                      FeedResultCategory = "MENTION"
	FeedResultCategoryDatasourceAffinity           FeedResultCategory = "DATASOURCE_AFFINITY"
	FeedResultCategoryRecent                       FeedResultCategory = "RECENT"
	FeedResultCategoryCompanyResource              FeedResultCategory = "COMPANY_RESOURCE"
	FeedResultCategoryExperimental                 FeedResultCategory = "EXPERIMENTAL"
	FeedResultCategoryPeopleCelebrations           FeedResultCategory = "PEOPLE_CELEBRATIONS"
	FeedResultCategorySocialLink                   FeedResultCategory = "SOCIAL_LINK"
	FeedResultCategoryExternalTasks                FeedResultCategory = "EXTERNAL_TASKS"
	FeedResultCategoryDisplayableList              FeedResultCategory = "DISPLAYABLE_LIST"
	FeedResultCategoryZeroStateChatSuggestion      FeedResultCategory = "ZERO_STATE_CHAT_SUGGESTION"
	FeedResultCategoryZeroStateChatToolSuggestion  FeedResultCategory = "ZERO_STATE_CHAT_TOOL_SUGGESTION"
	FeedResultCategoryZeroStateWorkflowCreatedByMe FeedResultCategory = "ZERO_STATE_WORKFLOW_CREATED_BY_ME"
	FeedResultCategoryZeroStateWorkflowFavorites   FeedResultCategory = "ZERO_STATE_WORKFLOW_FAVORITES"
	FeedResultCategoryZeroStateWorkflowPopular     FeedResultCategory = "ZERO_STATE_WORKFLOW_POPULAR"
	FeedResultCategoryZeroStateWorkflowRecent      FeedResultCategory = "ZERO_STATE_WORKFLOW_RECENT"
	FeedResultCategoryZeroStateWorkflowSuggestion  FeedResultCategory = "ZERO_STATE_WORKFLOW_SUGGESTION"
	FeedResultCategoryPersonalizedChatSuggestion   FeedResultCategory = "PERSONALIZED_CHAT_SUGGESTION"
	FeedResultCategoryDailyDigest                  FeedResultCategory = "DAILY_DIGEST"
	FeedResultCategoryPodcast                      FeedResultCategory = "PODCAST"
	FeedResultCategoryTask                         FeedResultCategory = "TASK"
	FeedResultCategoryPlanMyDay                    FeedResultCategory = "PLAN_MY_DAY"
	FeedResultCategoryEndMyDay                     FeedResultCategory = "END_MY_DAY"
	FeedResultCategoryStarterKit                   FeedResultCategory = "STARTER_KIT"
	FeedResultCategoryMidDayCatchUp                FeedResultCategory = "MID_DAY_CATCH_UP"
	FeedResultCategoryQuerySuggestion              FeedResultCategory = "QUERY_SUGGESTION"
	FeedResultCategoryCoworkCujPromo               FeedResultCategory = "COWORK_CUJ_PROMO"
	FeedResultCategoryCardStackPromo               FeedResultCategory = "CARD_STACK_PROMO"
	FeedResultCategoryWeeklyMeetings               FeedResultCategory = "WEEKLY_MEETINGS"
	FeedResultCategoryFollowUp                     FeedResultCategory = "FOLLOW_UP"
	FeedResultCategoryMilestoneTimelineCheck       FeedResultCategory = "MILESTONE_TIMELINE_CHECK"
	FeedResultCategoryProjectDiscussionDigest      FeedResultCategory = "PROJECT_DISCUSSION_DIGEST"
	FeedResultCategoryProjectFocusBlock            FeedResultCategory = "PROJECT_FOCUS_BLOCK"
	FeedResultCategoryProjectNextStep              FeedResultCategory = "PROJECT_NEXT_STEP"
	FeedResultCategoryDemoCard                     FeedResultCategory = "DEMO_CARD"
	FeedResultCategoryOooPlanner                   FeedResultCategory = "OOO_PLANNER"
	FeedResultCategoryOooCatchUp                   FeedResultCategory = "OOO_CATCH_UP"
	FeedResultCategoryAdminHealthCenter            FeedResultCategory = "ADMIN_HEALTH_CENTER"
)

func (e FeedResultCategory) ToPointer() *FeedResultCategory {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FeedResultCategory) IsExact() bool {
	if e != nil {
		switch *e {
		case "DOCUMENT_SUGGESTION", "DOCUMENT_SUGGESTION_SCENARIO", "TRENDING_DOCUMENT", "USE_CASE", "VERIFICATION_REMINDER", "EVENT", "ANNOUNCEMENT", "MENTION", "DATASOURCE_AFFINITY", "RECENT", "COMPANY_RESOURCE", "EXPERIMENTAL", "PEOPLE_CELEBRATIONS", "SOCIAL_LINK", "EXTERNAL_TASKS", "DISPLAYABLE_LIST", "ZERO_STATE_CHAT_SUGGESTION", "ZERO_STATE_CHAT_TOOL_SUGGESTION", "ZERO_STATE_WORKFLOW_CREATED_BY_ME", "ZERO_STATE_WORKFLOW_FAVORITES", "ZERO_STATE_WORKFLOW_POPULAR", "ZERO_STATE_WORKFLOW_RECENT", "ZERO_STATE_WORKFLOW_SUGGESTION", "PERSONALIZED_CHAT_SUGGESTION", "DAILY_DIGEST", "PODCAST", "TASK", "PLAN_MY_DAY", "END_MY_DAY", "STARTER_KIT", "MID_DAY_CATCH_UP", "QUERY_SUGGESTION", "COWORK_CUJ_PROMO", "CARD_STACK_PROMO", "WEEKLY_MEETINGS", "FOLLOW_UP", "MILESTONE_TIMELINE_CHECK", "PROJECT_DISCUSSION_DIGEST", "PROJECT_FOCUS_BLOCK", "PROJECT_NEXT_STEP", "DEMO_CARD", "OOO_PLANNER", "OOO_CATCH_UP", "ADMIN_HEALTH_CENTER":
			return true
		}
	}
	return false
}

// PlacementReason - Placement source for ranked feed results. ORGANIC means the card was emitted by normal feed ranking. PROMO means the card was inserted by the homepage cards promo framework.
type PlacementReason string

const (
	PlacementReasonOrganic PlacementReason = "ORGANIC"
	PlacementReasonPromo   PlacementReason = "PROMO"
)

func (e PlacementReason) ToPointer() *PlacementReason {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PlacementReason) IsExact() bool {
	if e != nil {
		switch *e {
		case "ORGANIC", "PROMO":
			return true
		}
	}
	return false
}

type FeedResult struct {
	// Category of the result, one of the requested categories in incoming request.
	Category     FeedResultCategory `json:"category"`
	PrimaryEntry FeedEntry          `json:"primaryEntry"`
	// Secondary entries for the result e.g. suggested docs for the calendar, carousel.
	SecondaryEntries []FeedEntry `json:"secondaryEntries,omitempty"`
	// Rank of the result. Rank is suggested by server. Client side rank may differ.
	Rank *int64 `json:"rank,omitempty"`
	// Placement source for ranked feed results. ORGANIC means the card was emitted by normal feed ranking. PROMO means the card was inserted by the homepage cards promo framework.
	PlacementReason *PlacementReason `json:"placementReason,omitempty"`
}

func (f *FeedResult) GetCategory() FeedResultCategory {
	if f == nil {
		return FeedResultCategory("")
	}
	return f.Category
}

func (f *FeedResult) GetPrimaryEntry() FeedEntry {
	if f == nil {
		return FeedEntry{}
	}
	return f.PrimaryEntry
}

func (f *FeedResult) GetSecondaryEntries() []FeedEntry {
	if f == nil {
		return nil
	}
	return f.SecondaryEntries
}

func (f *FeedResult) GetRank() *int64 {
	if f == nil {
		return nil
	}
	return f.Rank
}

func (f *FeedResult) GetPlacementReason() *PlacementReason {
	if f == nil {
		return nil
	}
	return f.PlacementReason
}
