// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetCollectionResponse struct {
	Collection     *Collection      `json:"collection,omitempty"`
	RootCollection *Collection      `json:"rootCollection,omitempty"`
	Error          *CollectionError `json:"error,omitempty"`
	// Use `collection.trackingToken` instead.
	//
	// Deprecated: Deprecated on 2026-05-07, removal scheduled for 2027-01-15: Use `collection.trackingToken` instead..
	TrackingToken *string `json:"trackingToken,omitempty"`
}

func (g *GetCollectionResponse) GetCollection() *Collection {
	if g == nil {
		return nil
	}
	return g.Collection
}

func (g *GetCollectionResponse) GetRootCollection() *Collection {
	if g == nil {
		return nil
	}
	return g.RootCollection
}

func (g *GetCollectionResponse) GetError() *CollectionError {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetCollectionResponse) GetTrackingToken() *string {
	if g == nil {
		return nil
	}
	return g.TrackingToken
}
