// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ImportAgentStatus - Outcome of the import for the target agent.
type ImportAgentStatus string

const (
	ImportAgentStatusCreated      ImportAgentStatus = "CREATED"
	ImportAgentStatusUpdated      ImportAgentStatus = "UPDATED"
	ImportAgentStatusDraftPreview ImportAgentStatus = "DRAFT_PREVIEW"
)

func (e ImportAgentStatus) ToPointer() *ImportAgentStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ImportAgentStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "CREATED", "UPDATED", "DRAFT_PREVIEW":
			return true
		}
	}
	return false
}
