// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Bundle struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (b *Bundle) GetFileName() string {
	if b == nil {
		return ""
	}
	return b.FileName
}

func (b *Bundle) GetContent() any {
	if b == nil {
		return nil
	}
	return b.Content
}

type ImportAgentRequest struct {
	// Zip of the agent folder (spec.yaml, instructions.md, skills/, subagents/) with symlinks dereferenced.
	//
	Bundle Bundle `multipartForm:"file,name=bundle"`
	// Optional Git commit SHA to associate with this import.
	GitCommitSha *string `multipartForm:"name=gitCommitSha"`
	// Optional VCS commit author ID to associate with this import.
	GitAuthorID *string `multipartForm:"name=gitAuthorId"`
	// Optional commit message for the imported version.
	CommitMessage *string `multipartForm:"name=commitMessage"`
	// Whether the imported version is staged (saved without updating the live version) or published directly to the live version.
	//
	SyncMode *ImportAgentSyncMode `multipartForm:"name=syncMode"`
	// When true, validates and stores a draft preview without publishing (used for PR preview links). Takes precedence over `syncMode`: when `isDraft` is true, `syncMode` is ignored.
	//
	IsDraft *bool `multipartForm:"name=isDraft"`
}

func (i *ImportAgentRequest) GetBundle() Bundle {
	if i == nil {
		return Bundle{}
	}
	return i.Bundle
}

func (i *ImportAgentRequest) GetGitCommitSha() *string {
	if i == nil {
		return nil
	}
	return i.GitCommitSha
}

func (i *ImportAgentRequest) GetGitAuthorID() *string {
	if i == nil {
		return nil
	}
	return i.GitAuthorID
}

func (i *ImportAgentRequest) GetCommitMessage() *string {
	if i == nil {
		return nil
	}
	return i.CommitMessage
}

func (i *ImportAgentRequest) GetSyncMode() *ImportAgentSyncMode {
	if i == nil {
		return nil
	}
	return i.SyncMode
}

func (i *ImportAgentRequest) GetIsDraft() *bool {
	if i == nil {
		return nil
	}
	return i.IsDraft
}
