// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type McpAuthMethodBreakdown struct {
	// Authentication method the MCP client presented, for example OAUTH_GLEAN, OAUTH_XAA (Cross App Access), or API_TOKEN.
	AuthMethod *string `json:"authMethod,omitempty"`
	// Total number of MCP calls for this authentication method in the specified time period.
	TotalCalls *int64 `json:"totalCalls,omitempty"`
	// Total number of active users for this authentication method in the specified time period.
	ActiveUsers *int64 `json:"activeUsers,omitempty"`
	// Host applications using this authentication method in the specified time period.
	HostApplications []string `json:"hostApplications,omitempty"`
}

func (m *McpAuthMethodBreakdown) GetAuthMethod() *string {
	if m == nil {
		return nil
	}
	return m.AuthMethod
}

func (m *McpAuthMethodBreakdown) GetTotalCalls() *int64 {
	if m == nil {
		return nil
	}
	return m.TotalCalls
}

func (m *McpAuthMethodBreakdown) GetActiveUsers() *int64 {
	if m == nil {
		return nil
	}
	return m.ActiveUsers
}

func (m *McpAuthMethodBreakdown) GetHostApplications() []string {
	if m == nil {
		return nil
	}
	return m.HostApplications
}
