// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type McpBreakdownInsightsResponse struct {
	UsersBreakdown            []McpUserBreakdown            `json:"usersBreakdown,omitempty"`
	HostApplicationsBreakdown []McpHostApplicationBreakdown `json:"hostApplicationsBreakdown,omitempty"`
	ToolsBreakdown            []McpToolBreakdown            `json:"toolsBreakdown,omitempty"`
	ServersBreakdown          []McpServerBreakdown          `json:"serversBreakdown,omitempty"`
}

func (m *McpBreakdownInsightsResponse) GetUsersBreakdown() []McpUserBreakdown {
	if m == nil {
		return nil
	}
	return m.UsersBreakdown
}

func (m *McpBreakdownInsightsResponse) GetHostApplicationsBreakdown() []McpHostApplicationBreakdown {
	if m == nil {
		return nil
	}
	return m.HostApplicationsBreakdown
}

func (m *McpBreakdownInsightsResponse) GetToolsBreakdown() []McpToolBreakdown {
	if m == nil {
		return nil
	}
	return m.ToolsBreakdown
}

func (m *McpBreakdownInsightsResponse) GetServersBreakdown() []McpServerBreakdown {
	if m == nil {
		return nil
	}
	return m.ServersBreakdown
}
