// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type McpToolBreakdown struct {
	// MCP tool name.
	Tool *string `json:"tool,omitempty"`
	// Total number of MCP calls for this tool in the specified time period.
	TotalCalls *int64 `json:"totalCalls,omitempty"`
	// Total number of active users for this tool in the specified time period.
	ActiveUsers *int64 `json:"activeUsers,omitempty"`
	// Host applications using this tool in the specified time period.
	HostApplications []string `json:"hostApplications,omitempty"`
}

func (m *McpToolBreakdown) GetTool() *string {
	if m == nil {
		return nil
	}
	return m.Tool
}

func (m *McpToolBreakdown) GetTotalCalls() *int64 {
	if m == nil {
		return nil
	}
	return m.TotalCalls
}

func (m *McpToolBreakdown) GetActiveUsers() *int64 {
	if m == nil {
		return nil
	}
	return m.ActiveUsers
}

func (m *McpToolBreakdown) GetHostApplications() []string {
	if m == nil {
		return nil
	}
	return m.HostApplications
}
