// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type PlatformTriggerPresetEventSearchRequest struct {
	// Values for the preset's input fields, keyed by field name.
	//
	Inputs map[string]string `json:"inputs,omitempty"`
	// Maximum number of events to return.
	PageSize *int64 `default:"10" json:"page_size"`
}

func (p PlatformTriggerPresetEventSearchRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformTriggerPresetEventSearchRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformTriggerPresetEventSearchRequest) GetInputs() map[string]string {
	if p == nil {
		return nil
	}
	return p.Inputs
}

func (p *PlatformTriggerPresetEventSearchRequest) GetPageSize() *int64 {
	if p == nil {
		return nil
	}
	return p.PageSize
}
