// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformTriggerListResponse struct {
	// Triggers owned by the caller.
	Results []PlatformTrigger `json:"results"`
	// Whether additional results are available.
	HasMore bool `json:"has_more"`
	// Cursor for the next page, or null when no more results are available.
	NextCursor *string `json:"next_cursor"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (p *PlatformTriggerListResponse) GetResults() []PlatformTrigger {
	if p == nil {
		return []PlatformTrigger{}
	}
	return p.Results
}

func (p *PlatformTriggerListResponse) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *PlatformTriggerListResponse) GetNextCursor() *string {
	if p == nil {
		return nil
	}
	return p.NextCursor
}

func (p *PlatformTriggerListResponse) GetRequestID() string {
	if p == nil {
		return ""
	}
	return p.RequestID
}
