// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type PlatformSkillSourcePreviewStreamSkillServerSentEvent struct {
	ID *string `json:"id,omitempty"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	event string `const:"SKILL" json:"event"`
	// One skill previewed; carries the previewed skill.
	Data PlatformSkillSourcePreviewStreamSkill `json:"data"`
}

func (p PlatformSkillSourcePreviewStreamSkillServerSentEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkillSourcePreviewStreamSkillServerSentEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformSkillSourcePreviewStreamSkillServerSentEvent) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PlatformSkillSourcePreviewStreamSkillServerSentEvent) GetEvent() string {
	return "SKILL"
}

func (p *PlatformSkillSourcePreviewStreamSkillServerSentEvent) GetData() PlatformSkillSourcePreviewStreamSkill {
	if p == nil {
		return PlatformSkillSourcePreviewStreamSkill{}
	}
	return p.Data
}
