// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformAgentRunWaitResponse struct {
	Run *PlatformAgentRun `json:"run,omitempty"`
	// Messages returned by the completed run.
	Messages []PlatformMessage `json:"messages,omitempty"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (p *PlatformAgentRunWaitResponse) GetRun() *PlatformAgentRun {
	if p == nil {
		return nil
	}
	return p.Run
}

func (p *PlatformAgentRunWaitResponse) GetMessages() []PlatformMessage {
	if p == nil {
		return nil
	}
	return p.Messages
}

func (p *PlatformAgentRunWaitResponse) GetRequestID() string {
	if p == nil {
		return ""
	}
	return p.RequestID
}
