// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformTriggerPresetInput struct {
	// Identifier of the input, supplied as a key in the trigger's `inputs`.
	Field string `json:"field"`
	// Type of a preset input.
	Type PlatformTriggerPresetInputType `json:"type"`
	// Human-readable name for the input.
	DisplayName string `json:"display_name"`
	// Whether the caller must supply a value for this input.
	IsRequired bool `json:"is_required"`
	// Bounded initial set of selectable values for a picklist input. Omitted entirely for free-text inputs.
	//
	Values []PlatformTriggerPresetInputValue `json:"values,omitempty"`
	// Whether additional selectable values were omitted from `values`. When true, use GET /trigger-presets/{preset_id}/input-values with a query to narrow the result set.
	//
	IsTruncated *bool `json:"is_truncated,omitempty"`
}

func (p *PlatformTriggerPresetInput) GetField() string {
	if p == nil {
		return ""
	}
	return p.Field
}

func (p *PlatformTriggerPresetInput) GetType() PlatformTriggerPresetInputType {
	if p == nil {
		return PlatformTriggerPresetInputType("")
	}
	return p.Type
}

func (p *PlatformTriggerPresetInput) GetDisplayName() string {
	if p == nil {
		return ""
	}
	return p.DisplayName
}

func (p *PlatformTriggerPresetInput) GetIsRequired() bool {
	if p == nil {
		return false
	}
	return p.IsRequired
}

func (p *PlatformTriggerPresetInput) GetValues() []PlatformTriggerPresetInputValue {
	if p == nil {
		return nil
	}
	return p.Values
}

func (p *PlatformTriggerPresetInput) GetIsTruncated() *bool {
	if p == nil {
		return nil
	}
	return p.IsTruncated
}
