// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PlatformMessageRole - Role of the message author.
type PlatformMessageRole string

const (
	PlatformMessageRoleUser    PlatformMessageRole = "USER"
	PlatformMessageRoleGleanAi PlatformMessageRole = "GLEAN_AI"
)

func (e PlatformMessageRole) ToPointer() *PlatformMessageRole {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PlatformMessageRole) IsExact() bool {
	if e != nil {
		switch *e {
		case "USER", "GLEAN_AI":
			return true
		}
	}
	return false
}
