// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
)

// PlatformSkillSourcePreviewStreamSkillType - Event type, also sent as the SSE `event` name.
type PlatformSkillSourcePreviewStreamSkillType string

const (
	PlatformSkillSourcePreviewStreamSkillTypeSkill PlatformSkillSourcePreviewStreamSkillType = "SKILL"
)

func (e PlatformSkillSourcePreviewStreamSkillType) ToPointer() *PlatformSkillSourcePreviewStreamSkillType {
	return &e
}
func (e *PlatformSkillSourcePreviewStreamSkillType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SKILL":
		*e = PlatformSkillSourcePreviewStreamSkillType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformSkillSourcePreviewStreamSkillType: %v", v)
	}
}

// PlatformSkillSourcePreviewStreamSkill - One skill previewed; carries the previewed skill.
type PlatformSkillSourcePreviewStreamSkill struct {
	// Event type, also sent as the SSE `event` name.
	Type  PlatformSkillSourcePreviewStreamSkillType `json:"type"`
	Skill PlatformSkillSourcePreview                `json:"skill"`
}

func (p PlatformSkillSourcePreviewStreamSkill) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkillSourcePreviewStreamSkill) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformSkillSourcePreviewStreamSkill) GetType() PlatformSkillSourcePreviewStreamSkillType {
	if p == nil {
		return PlatformSkillSourcePreviewStreamSkillType("")
	}
	return p.Type
}

func (p *PlatformSkillSourcePreviewStreamSkill) GetSkill() PlatformSkillSourcePreview {
	if p == nil {
		return PlatformSkillSourcePreview{}
	}
	return p.Skill
}
