// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
)

// PlatformSkillSourcePreviewStreamResultType - Event type, also sent as the SSE `event` name.
type PlatformSkillSourcePreviewStreamResultType string

const (
	PlatformSkillSourcePreviewStreamResultTypeResult PlatformSkillSourcePreviewStreamResultType = "RESULT"
)

func (e PlatformSkillSourcePreviewStreamResultType) ToPointer() *PlatformSkillSourcePreviewStreamResultType {
	return &e
}
func (e *PlatformSkillSourcePreviewStreamResultType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "RESULT":
		*e = PlatformSkillSourcePreviewStreamResultType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformSkillSourcePreviewStreamResultType: %v", v)
	}
}

// PlatformSkillSourcePreviewStreamResult - Terminal success event carrying the fully assembled preview.
type PlatformSkillSourcePreviewStreamResult struct {
	// Event type, also sent as the SSE `event` name.
	Type     PlatformSkillSourcePreviewStreamResultType `json:"type"`
	Response PlatformSkillSourcePreviewResponse         `json:"response"`
}

func (p PlatformSkillSourcePreviewStreamResult) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkillSourcePreviewStreamResult) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformSkillSourcePreviewStreamResult) GetType() PlatformSkillSourcePreviewStreamResultType {
	if p == nil {
		return PlatformSkillSourcePreviewStreamResultType("")
	}
	return p.Type
}

func (p *PlatformSkillSourcePreviewStreamResult) GetResponse() PlatformSkillSourcePreviewResponse {
	if p == nil {
		return PlatformSkillSourcePreviewResponse{}
	}
	return p.Response
}
