// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformSkillValidationResponse struct {
	Metadata PlatformSkillValidationMetadata `json:"metadata"`
	// Normalized files in the bundle after stripping an optional single root folder.
	Files []PlatformSkillValidationFile `json:"files"`
	// Non-blocking validation warnings.
	Warnings []PlatformSkillValidationWarning `json:"warnings"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (p *PlatformSkillValidationResponse) GetMetadata() PlatformSkillValidationMetadata {
	if p == nil {
		return PlatformSkillValidationMetadata{}
	}
	return p.Metadata
}

func (p *PlatformSkillValidationResponse) GetFiles() []PlatformSkillValidationFile {
	if p == nil {
		return []PlatformSkillValidationFile{}
	}
	return p.Files
}

func (p *PlatformSkillValidationResponse) GetWarnings() []PlatformSkillValidationWarning {
	if p == nil {
		return []PlatformSkillValidationWarning{}
	}
	return p.Warnings
}

func (p *PlatformSkillValidationResponse) GetRequestID() string {
	if p == nil {
		return ""
	}
	return p.RequestID
}
