// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PlatformUserManager - The user that another user reports to.
type PlatformUserManager struct {
	// Opaque canonical Glean user ID of the manager.
	UserID string `json:"user_id"`
	// The name that Glean shows for the manager.
	DisplayName string `json:"display_name"`
}

func (p *PlatformUserManager) GetUserID() string {
	if p == nil {
		return ""
	}
	return p.UserID
}

func (p *PlatformUserManager) GetDisplayName() string {
	if p == nil {
		return ""
	}
	return p.DisplayName
}
