// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformAgentRun struct {
	// ID of the agent being run.
	AgentID string `json:"agent_id"`
	// Input fields for an input-form triggered agent.
	Input map[string]any `json:"input,omitempty"`
	// Messages passed to the agent.
	Messages []PlatformMessage `json:"messages,omitempty"`
	// Metadata passed to the agent.
	Metadata map[string]any `json:"metadata,omitempty"`
	// Status of the agent run.
	Status PlatformAgentExecutionStatus `json:"status"`
}

func (p *PlatformAgentRun) GetAgentID() string {
	if p == nil {
		return ""
	}
	return p.AgentID
}

func (p *PlatformAgentRun) GetInput() map[string]any {
	if p == nil {
		return nil
	}
	return p.Input
}

func (p *PlatformAgentRun) GetMessages() []PlatformMessage {
	if p == nil {
		return nil
	}
	return p.Messages
}

func (p *PlatformAgentRun) GetMetadata() map[string]any {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *PlatformAgentRun) GetStatus() PlatformAgentExecutionStatus {
	if p == nil {
		return PlatformAgentExecutionStatus("")
	}
	return p.Status
}
