// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformSkillValidationRequestFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (p *PlatformSkillValidationRequestFile) GetFileName() string {
	if p == nil {
		return ""
	}
	return p.FileName
}

func (p *PlatformSkillValidationRequestFile) GetContent() any {
	if p == nil {
		return nil
	}
	return p.Content
}

type PlatformSkillValidationRequest struct {
	// SKILL.md, .zip, or .skill bundle to validate.
	File PlatformSkillValidationRequestFile `multipartForm:"file,name=file"`
}

func (p *PlatformSkillValidationRequest) GetFile() PlatformSkillValidationRequestFile {
	if p == nil {
		return PlatformSkillValidationRequestFile{}
	}
	return p.File
}
