// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformSkillCreateResponse struct {
	Skill PlatformSkill `json:"skill"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (p *PlatformSkillCreateResponse) GetSkill() PlatformSkill {
	if p == nil {
		return PlatformSkill{}
	}
	return p.Skill
}

func (p *PlatformSkillCreateResponse) GetRequestID() string {
	if p == nil {
		return ""
	}
	return p.RequestID
}
