// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
	"time"
)

type PlatformSkill struct {
	// Glean skill ID.
	SkillID string `json:"skill_id"`
	// Human-readable skill name.
	DisplayName string `json:"display_name"`
	// Human-readable skill description.
	Description string `json:"description"`
	// Latest major version number for the skill.
	LatestVersion int64 `json:"latest_version"`
	// Latest minor version number for the skill.
	LatestMinorVersion int64 `json:"latest_minor_version"`
	// The caller's effective activation. The owner sees the skill's stored status. Another caller sees their personal setting, or DISABLED when they have none. DRAFT is the stored draft state and is not set by update. Effective activation may also reflect workspace governance policy.
	//
	Status PlatformSkillStatus `json:"status"`
	// Source category for the skill.
	Origin           PlatformSkillOrigin            `json:"origin"`
	SourceProvenance *PlatformSkillSourceProvenance `json:"source_provenance,omitempty"`
	// A lightweight reference to a person, used where a payload merely points at someone.
	Owner PlatformPersonReference `json:"owner"`
	// Time the skill was created.
	CreatedAt time.Time `json:"created_at"`
	// Time the skill was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (p PlatformSkill) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkill) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformSkill) GetSkillID() string {
	if p == nil {
		return ""
	}
	return p.SkillID
}

func (p *PlatformSkill) GetDisplayName() string {
	if p == nil {
		return ""
	}
	return p.DisplayName
}

func (p *PlatformSkill) GetDescription() string {
	if p == nil {
		return ""
	}
	return p.Description
}

func (p *PlatformSkill) GetLatestVersion() int64 {
	if p == nil {
		return 0
	}
	return p.LatestVersion
}

func (p *PlatformSkill) GetLatestMinorVersion() int64 {
	if p == nil {
		return 0
	}
	return p.LatestMinorVersion
}

func (p *PlatformSkill) GetStatus() PlatformSkillStatus {
	if p == nil {
		return PlatformSkillStatus("")
	}
	return p.Status
}

func (p *PlatformSkill) GetOrigin() PlatformSkillOrigin {
	if p == nil {
		return PlatformSkillOrigin("")
	}
	return p.Origin
}

func (p *PlatformSkill) GetSourceProvenance() *PlatformSkillSourceProvenance {
	if p == nil {
		return nil
	}
	return p.SourceProvenance
}

func (p *PlatformSkill) GetOwner() PlatformPersonReference {
	if p == nil {
		return PlatformPersonReference{}
	}
	return p.Owner
}

func (p *PlatformSkill) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PlatformSkill) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}
