// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type PlatformTriggerEventSearchRequest struct {
	// Maximum number of events to return.
	PageSize *int64 `default:"10" json:"page_size"`
}

func (p PlatformTriggerEventSearchRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformTriggerEventSearchRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformTriggerEventSearchRequest) GetPageSize() *int64 {
	if p == nil {
		return nil
	}
	return p.PageSize
}
