// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformSkillSourcePreviewFile struct {
	// Relative path within the skill bundle.
	Path string `json:"path"`
	// UTF-8 file content.
	Content string `json:"content"`
}

func (p *PlatformSkillSourcePreviewFile) GetPath() string {
	if p == nil {
		return ""
	}
	return p.Path
}

func (p *PlatformSkillSourcePreviewFile) GetContent() string {
	if p == nil {
		return ""
	}
	return p.Content
}
