// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformSkillImportRequest struct {
	// Resolved GitHub skill URLs selected from a source preview.
	SourceUrls []string `json:"source_urls"`
}

func (p *PlatformSkillImportRequest) GetSourceUrls() []string {
	if p == nil {
		return []string{}
	}
	return p.SourceUrls
}
