// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformTriggerPresetInputValueListResponse struct {
	// The bounded set of selectable values matching the query.
	Results []PlatformTriggerPresetInputValue `json:"results"`
	// Whether additional matches were omitted. When true, refine `query` to narrow the result set.
	//
	IsTruncated bool `json:"is_truncated"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (p *PlatformTriggerPresetInputValueListResponse) GetResults() []PlatformTriggerPresetInputValue {
	if p == nil {
		return []PlatformTriggerPresetInputValue{}
	}
	return p.Results
}

func (p *PlatformTriggerPresetInputValueListResponse) GetIsTruncated() bool {
	if p == nil {
		return false
	}
	return p.IsTruncated
}

func (p *PlatformTriggerPresetInputValueListResponse) GetRequestID() string {
	if p == nil {
		return ""
	}
	return p.RequestID
}
