// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
)

type PlatformChatStreamResponseCreatedType string

const (
	PlatformChatStreamResponseCreatedTypeResponseCreated PlatformChatStreamResponseCreatedType = "RESPONSE_CREATED"
)

func (e PlatformChatStreamResponseCreatedType) ToPointer() *PlatformChatStreamResponseCreatedType {
	return &e
}
func (e *PlatformChatStreamResponseCreatedType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "RESPONSE_CREATED":
		*e = PlatformChatStreamResponseCreatedType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformChatStreamResponseCreatedType: %v", v)
	}
}

type PlatformChatStreamResponseCreated struct {
	Type PlatformChatStreamResponseCreatedType `json:"type"`
	// Platform-owned, non-persisted response envelope identifier in `resp_<uuid>` form. The same identifier is used for every event in one streamed response.
	//
	ResponseID string `json:"response_id"`
}

func (p PlatformChatStreamResponseCreated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformChatStreamResponseCreated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformChatStreamResponseCreated) GetType() PlatformChatStreamResponseCreatedType {
	if p == nil {
		return PlatformChatStreamResponseCreatedType("")
	}
	return p.Type
}

func (p *PlatformChatStreamResponseCreated) GetResponseID() string {
	if p == nil {
		return ""
	}
	return p.ResponseID
}
