// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformTriggerGetResponse struct {
	Trigger PlatformTrigger `json:"trigger"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (p *PlatformTriggerGetResponse) GetTrigger() PlatformTrigger {
	if p == nil {
		return PlatformTrigger{}
	}
	return p.Trigger
}

func (p *PlatformTriggerGetResponse) GetRequestID() string {
	if p == nil {
		return ""
	}
	return p.RequestID
}
