// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformChatCitationSnippet struct {
	Text       string `json:"text"`
	PageNumber *int64 `json:"page_number,omitempty"`
}

func (p *PlatformChatCitationSnippet) GetText() string {
	if p == nil {
		return ""
	}
	return p.Text
}

func (p *PlatformChatCitationSnippet) GetPageNumber() *int64 {
	if p == nil {
		return nil
	}
	return p.PageNumber
}
