// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
)

type PlatformChatOutputTextContentType string

const (
	PlatformChatOutputTextContentTypeOutputText PlatformChatOutputTextContentType = "OUTPUT_TEXT"
)

func (e PlatformChatOutputTextContentType) ToPointer() *PlatformChatOutputTextContentType {
	return &e
}
func (e *PlatformChatOutputTextContentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OUTPUT_TEXT":
		*e = PlatformChatOutputTextContentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformChatOutputTextContentType: %v", v)
	}
}

type PlatformChatOutputTextContent struct {
	Type        PlatformChatOutputTextContentType `json:"type"`
	Text        string                            `json:"text"`
	Annotations []PlatformChatCitationAnnotation  `json:"annotations,omitempty"`
}

func (p PlatformChatOutputTextContent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformChatOutputTextContent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformChatOutputTextContent) GetType() PlatformChatOutputTextContentType {
	if p == nil {
		return PlatformChatOutputTextContentType("")
	}
	return p.Type
}

func (p *PlatformChatOutputTextContent) GetText() string {
	if p == nil {
		return ""
	}
	return p.Text
}

func (p *PlatformChatOutputTextContent) GetAnnotations() []PlatformChatCitationAnnotation {
	if p == nil {
		return nil
	}
	return p.Annotations
}
