// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type PlatformSearchRequest struct {
	// The search query string. Supports inline operators such as `from:jane type:document app:confluence`. Inline operators are AND'd with structured `filters`.
	//
	Query string `json:"query"`
	// Number of results to return per page.
	PageSize *int64 `default:"10" json:"page_size"`
	// Opaque pagination token from a previous response's `next_cursor` field. Omit on the first request.
	//
	Cursor *string `json:"cursor,omitempty"`
	// Restrict results to specific datasource identifiers returned by `GET /api/search/filters`. Scopes by datasource type and may include results from multiple instances of that type.
	//
	Datasources []string `json:"datasources,omitempty"`
	// Structured filters applied to search results. Multiple values within a filter with `EQUALS` are OR'd; separate filters are AND'd. Conflicting constraints on the same field (for example, `type:document` in `query` and `type:spreadsheet` in a filter) return an empty result set. See `Filter.field` for built-in field names and operators. Other nonblank field names are accepted as custom filters without validation; behavior depends on your connected sources.
	//
	Filters []PlatformFilter `json:"filters,omitempty"`
	// Filter results to those last updated within this range.
	TimeRange *PlatformTimeRange `json:"time_range,omitempty"`
}

func (p PlatformSearchRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSearchRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformSearchRequest) GetQuery() string {
	if p == nil {
		return ""
	}
	return p.Query
}

func (p *PlatformSearchRequest) GetPageSize() *int64 {
	if p == nil {
		return nil
	}
	return p.PageSize
}

func (p *PlatformSearchRequest) GetCursor() *string {
	if p == nil {
		return nil
	}
	return p.Cursor
}

func (p *PlatformSearchRequest) GetDatasources() []string {
	if p == nil {
		return nil
	}
	return p.Datasources
}

func (p *PlatformSearchRequest) GetFilters() []PlatformFilter {
	if p == nil {
		return nil
	}
	return p.Filters
}

func (p *PlatformSearchRequest) GetTimeRange() *PlatformTimeRange {
	if p == nil {
		return nil
	}
	return p.TimeRange
}
