// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformMessageTextBlockInput struct {
	// Text content.
	Text string              `json:"text"`
	Type PlatformContentType `json:"type"`
}

func (p *PlatformMessageTextBlockInput) GetText() string {
	if p == nil {
		return ""
	}
	return p.Text
}

func (p *PlatformMessageTextBlockInput) GetType() PlatformContentType {
	if p == nil {
		return PlatformContentType("")
	}
	return p.Type
}
