// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
	"time"
)

// PlatformDurableAgentRun - Agent run state, pending tool approvals, and output available independently of the creation request.
type PlatformDurableAgentRun struct {
	// ID of the run, preserved across approval continuations.
	RunID string `json:"run_id"`
	// ID of the agent that owns the run.
	AgentID string `json:"agent_id"`
	// State of the persisted workflow execution. REQUIRES_INPUT is nonterminal.
	State PlatformAgentRunState `json:"state"`
	// Timestamp when the run was first persisted.
	CreatedAt time.Time `json:"created_at"`
	// Latest persisted activity timestamp across the execution and its messages, including checkpoint messages. This is not a worker heartbeat or an exact state-transition timestamp.
	//
	UpdatedAt time.Time `json:"updated_at"`
	// Execution deadline, when one is set. Not the run history retention deadline.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Unanswered tool approvals when the run is in REQUIRES_INPUT. Empty in other states.
	PendingInteractions []PlatformAgentRunToolApproval `json:"pending_interactions"`
	// Accumulated text-only agent output under the messages key, when available.
	Output map[string]any `json:"output,omitempty"`
	// Caller-safe details of an agent run execution failure.
	Error *PlatformAgentRunError `json:"error,omitempty"`
}

func (p PlatformDurableAgentRun) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformDurableAgentRun) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformDurableAgentRun) GetRunID() string {
	if p == nil {
		return ""
	}
	return p.RunID
}

func (p *PlatformDurableAgentRun) GetAgentID() string {
	if p == nil {
		return ""
	}
	return p.AgentID
}

func (p *PlatformDurableAgentRun) GetState() PlatformAgentRunState {
	if p == nil {
		return PlatformAgentRunState("")
	}
	return p.State
}

func (p *PlatformDurableAgentRun) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PlatformDurableAgentRun) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *PlatformDurableAgentRun) GetExpiresAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.ExpiresAt
}

func (p *PlatformDurableAgentRun) GetPendingInteractions() []PlatformAgentRunToolApproval {
	if p == nil {
		return []PlatformAgentRunToolApproval{}
	}
	return p.PendingInteractions
}

func (p *PlatformDurableAgentRun) GetOutput() map[string]any {
	if p == nil {
		return nil
	}
	return p.Output
}

func (p *PlatformDurableAgentRun) GetError() *PlatformAgentRunError {
	if p == nil {
		return nil
	}
	return p.Error
}
