// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PlatformTriggerStatus - Current trigger lifecycle state.
type PlatformTriggerStatus string

const (
	PlatformTriggerStatusEnabled  PlatformTriggerStatus = "ENABLED"
	PlatformTriggerStatusDisabled PlatformTriggerStatus = "DISABLED"
)

func (e PlatformTriggerStatus) ToPointer() *PlatformTriggerStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PlatformTriggerStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "ENABLED", "DISABLED":
			return true
		}
	}
	return false
}
