// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

// PlatformProblemDetail - Error response following RFC 9457, extended with `code` and `documentation_url` for machine-readable classification and self-service remediation.
type PlatformProblemDetail struct {
	// URI identifying the error type.
	Type string `json:"type"`
	// Short, human-readable summary of the error.
	Title string `json:"title"`
	// HTTP status code mirrored from the response.
	Status int64 `json:"status"`
	// Human-readable explanation specific to this occurrence.
	Detail string `json:"detail"`
	// Stable machine-readable error code.
	Code PlatformProblemDetailCode `json:"code"`
	// Direct URL to documentation for this error code.
	DocumentationURL *string `json:"documentation_url,omitempty"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
	// Field-level validation problems, one entry per offending field.
	Errors []PlatformProblemDetailError `json:"errors,omitempty"`
}

func (p PlatformProblemDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformProblemDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformProblemDetail) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *PlatformProblemDetail) GetTitle() string {
	if p == nil {
		return ""
	}
	return p.Title
}

func (p *PlatformProblemDetail) GetStatus() int64 {
	if p == nil {
		return 0
	}
	return p.Status
}

func (p *PlatformProblemDetail) GetDetail() string {
	if p == nil {
		return ""
	}
	return p.Detail
}

func (p *PlatformProblemDetail) GetCode() PlatformProblemDetailCode {
	if p == nil {
		return PlatformProblemDetailCode("")
	}
	return p.Code
}

func (p *PlatformProblemDetail) GetDocumentationURL() *string {
	if p == nil {
		return nil
	}
	return p.DocumentationURL
}

func (p *PlatformProblemDetail) GetRequestID() string {
	if p == nil {
		return ""
	}
	return p.RequestID
}

func (p *PlatformProblemDetail) GetErrors() []PlatformProblemDetailError {
	if p == nil {
		return nil
	}
	return p.Errors
}
