// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformSkillImportResponse struct {
	// Independently persisted skills in request order.
	Skills []PlatformSkill `json:"skills"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (p *PlatformSkillImportResponse) GetSkills() []PlatformSkill {
	if p == nil {
		return []PlatformSkill{}
	}
	return p.Skills
}

func (p *PlatformSkillImportResponse) GetRequestID() string {
	if p == nil {
		return ""
	}
	return p.RequestID
}
