// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformSkillVersionCreateRequestFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (p *PlatformSkillVersionCreateRequestFile) GetFileName() string {
	if p == nil {
		return ""
	}
	return p.FileName
}

func (p *PlatformSkillVersionCreateRequestFile) GetContent() any {
	if p == nil {
		return nil
	}
	return p.Content
}

type PlatformSkillVersionCreateRequest struct {
	// SKILL.md, .zip, or .skill bundle to store as a new version.
	File PlatformSkillVersionCreateRequestFile `multipartForm:"file,name=file"`
}

func (p *PlatformSkillVersionCreateRequest) GetFile() PlatformSkillVersionCreateRequestFile {
	if p == nil {
		return PlatformSkillVersionCreateRequestFile{}
	}
	return p.File
}
