// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PlatformPersonReference - A lightweight reference to a person, used where a payload merely points at someone.
type PlatformPersonReference struct {
	// Opaque Glean person ID.
	ID *string `json:"id,omitempty"`
	// Display name.
	Name string `json:"name"`
}

func (p *PlatformPersonReference) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PlatformPersonReference) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}
