// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformTriggerPresetInputValue struct {
	// The exact value to send in the trigger's `inputs` for this choice (e.g. a channel name, a user's email, etc).
	//
	Value string `json:"value"`
	// Human-readable name for this value.
	DisplayName string `json:"display_name"`
}

func (p *PlatformTriggerPresetInputValue) GetValue() string {
	if p == nil {
		return ""
	}
	return p.Value
}

func (p *PlatformTriggerPresetInputValue) GetDisplayName() string {
	if p == nil {
		return ""
	}
	return p.DisplayName
}
