// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PlatformSkillCreateRequestFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (p *PlatformSkillCreateRequestFile) GetFileName() string {
	if p == nil {
		return ""
	}
	return p.FileName
}

func (p *PlatformSkillCreateRequestFile) GetContent() any {
	if p == nil {
		return nil
	}
	return p.Content
}

type PlatformSkillCreateRequest struct {
	// SKILL.md, .zip, or .skill bundle to create.
	File PlatformSkillCreateRequestFile `multipartForm:"file,name=file"`
}

func (p *PlatformSkillCreateRequest) GetFile() PlatformSkillCreateRequestFile {
	if p == nil {
		return PlatformSkillCreateRequestFile{}
	}
	return p.File
}
