// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

type PlatformSkillSourcePreviewFailure struct {
	// Resolved URL for the entry that could not be previewed.
	SourceURL string `json:"source_url"`
	// Stable machine-readable reason a discovered entry was excluded.
	Code PlatformSkillSourcePreviewFailureCode `json:"code"`
	// Safe explanation of why the entry was excluded.
	Detail string `json:"detail"`
}

func (p PlatformSkillSourcePreviewFailure) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkillSourcePreviewFailure) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformSkillSourcePreviewFailure) GetSourceURL() string {
	if p == nil {
		return ""
	}
	return p.SourceURL
}

func (p *PlatformSkillSourcePreviewFailure) GetCode() PlatformSkillSourcePreviewFailureCode {
	if p == nil {
		return PlatformSkillSourcePreviewFailureCode("")
	}
	return p.Code
}

func (p *PlatformSkillSourcePreviewFailure) GetDetail() string {
	if p == nil {
		return ""
	}
	return p.Detail
}
