// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PlatformAgentExecutionStatus - Status of the agent run.
type PlatformAgentExecutionStatus string

const (
	PlatformAgentExecutionStatusError   PlatformAgentExecutionStatus = "error"
	PlatformAgentExecutionStatusSuccess PlatformAgentExecutionStatus = "success"
)

func (e PlatformAgentExecutionStatus) ToPointer() *PlatformAgentExecutionStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PlatformAgentExecutionStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "error", "success":
			return true
		}
	}
	return false
}
