// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/gleanwork/api-client-go/internal/utils"
)

// ServerToolResponseRequestType - The type of request made to the user.
type ServerToolResponseRequestType string

const (
	// ServerToolResponseRequestTypeExecution Request for approving execution of the tool.
	ServerToolResponseRequestTypeExecution ServerToolResponseRequestType = "EXECUTION"
	// ServerToolResponseRequestTypeAuthenticationSuggestion Request for authenticating to a tool, provided as a (tool) suggestion.
	ServerToolResponseRequestTypeAuthenticationSuggestion ServerToolResponseRequestType = "AUTHENTICATION_SUGGESTION"
	// ServerToolResponseRequestTypeVoteSuggestion Suggestion to vote for enabling an available-but-not-enabled tool.
	ServerToolResponseRequestTypeVoteSuggestion ServerToolResponseRequestType = "VOTE_SUGGESTION"
)

func (e ServerToolResponseRequestType) ToPointer() *ServerToolResponseRequestType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ServerToolResponseRequestType) IsExact() bool {
	if e != nil {
		switch *e {
		case "EXECUTION", "AUTHENTICATION_SUGGESTION", "VOTE_SUGGESTION":
			return true
		}
	}
	return false
}

// GrantScope - Scope of the approval grant. Only applicable when isGranted is true and requestType is EXECUTION.
type GrantScope string

const (
	// GrantScopeCurrentRequest Approve only the current tool request. Future tool execution requests still require approval.
	GrantScopeCurrentRequest GrantScope = "CURRENT_REQUEST"
	// GrantScopeCurrentSession Approve the current tool request and auto-approve all future same tool requests in this chat session.
	GrantScopeCurrentSession GrantScope = "CURRENT_SESSION"
	// GrantScopeAlways Approve the current tool request and auto-approve all future same tool requests across all chat sessions.
	GrantScopeAlways GrantScope = "ALWAYS"
)

func (e GrantScope) ToPointer() *GrantScope {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GrantScope) IsExact() bool {
	if e != nil {
		switch *e {
		case "CURRENT_REQUEST", "CURRENT_SESSION", "ALWAYS":
			return true
		}
	}
	return false
}

// ServerToolResponse - Response to a server tool request. The applicable fields depend on requestType:
//
// For EXECUTION requests:
// - isGranted: whether tool execution is approved
// - reason: optional explanation
//
// For AUTHENTICATION_SUGGESTION requests:
// - isGranted: whether auth completed successfully (true=connected, false=skipped)
// - authContext: contains serverId or actionPackId for identifying the authenticated entity
// - reason: optional explanation for skip
//
// For VOTE_SUGGESTION requests:
// - voted: whether the user voted for this tool
type ServerToolResponse struct {
	// The type of request made to the user.
	RequestType ServerToolResponseRequestType `json:"requestType"`
	// Unique identifier for this request.
	RequestID string `json:"requestId"`
	// Whether tool request is granted (indicates approval for execution, or completion for auth).
	IsGranted *bool `json:"isGranted,omitempty"`
	// Scope of the approval grant. Only applicable when isGranted is true and requestType is EXECUTION.
	//
	GrantScope *GrantScope `default:"CURRENT_REQUEST" json:"grantScope"`
	// Context for authentication responses, containing identifiers for the entity being authenticated.
	//
	AuthContext *AuthContext `json:"authContext,omitempty"`
}

func (s ServerToolResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServerToolResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ServerToolResponse) GetRequestType() ServerToolResponseRequestType {
	if s == nil {
		return ServerToolResponseRequestType("")
	}
	return s.RequestType
}

func (s *ServerToolResponse) GetRequestID() string {
	if s == nil {
		return ""
	}
	return s.RequestID
}

func (s *ServerToolResponse) GetIsGranted() *bool {
	if s == nil {
		return nil
	}
	return s.IsGranted
}

func (s *ServerToolResponse) GetGrantScope() *GrantScope {
	if s == nil {
		return nil
	}
	return s.GrantScope
}

func (s *ServerToolResponse) GetAuthContext() *AuthContext {
	if s == nil {
		return nil
	}
	return s.AuthContext
}
