// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ToolDefinition struct {
	// Tool server this tool belongs to.
	ServerID string `json:"serverId"`
	// Name to invoke the tool by.
	Name string `json:"name"`
	// Human-readable name of the tool.
	DisplayName *string `json:"displayName,omitempty"`
	// What the tool does, as surfaced to a model.
	Description *string `json:"description,omitempty"`
	// JSON Schema for the tool's input parameters.
	InputSchema map[string]any `json:"inputSchema,omitempty"`
	// Behavioural hints for the tool, exactly as declared by the tool server. No
	// defaults are filled in — see the per-field notes for what an absent value means.
	//
	// Per the MCP specification, clients MUST treat these hints as untrusted unless
	// the tool server is itself trusted. They are advisory metadata, not an
	// authorization signal, and must not be the sole basis of a security decision.
	//
	Annotations *ToolAnnotations `json:"annotations,omitempty"`
}

func (t *ToolDefinition) GetServerID() string {
	if t == nil {
		return ""
	}
	return t.ServerID
}

func (t *ToolDefinition) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *ToolDefinition) GetDisplayName() *string {
	if t == nil {
		return nil
	}
	return t.DisplayName
}

func (t *ToolDefinition) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *ToolDefinition) GetInputSchema() map[string]any {
	if t == nil {
		return nil
	}
	return t.InputSchema
}

func (t *ToolDefinition) GetAnnotations() *ToolAnnotations {
	if t == nil {
		return nil
	}
	return t.Annotations
}
