// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ToolAnnotations - Behavioural hints for the tool, exactly as declared by the tool server. No
// defaults are filled in — see the per-field notes for what an absent value means.
//
// Per the MCP specification, clients MUST treat these hints as untrusted unless
// the tool server is itself trusted. They are advisory metadata, not an
// authorization signal, and must not be the sole basis of a security decision.
type ToolAnnotations struct {
	Title *string `json:"title,omitempty"`
	// True if the tool does not modify its environment. Always present. MCP
	// defines no distinction between an undeclared value and `false` here, so
	// `false` means "not declared read-only" rather than "declared mutating".
	//
	ReadOnlyHint *bool `json:"readOnlyHint,omitempty"`
	// True if the tool may perform destructive updates. **Absent means the server
	// did not declare it**, for which the MCP default is `true`. Only meaningful
	// when `readOnlyHint` is `false`.
	//
	DestructiveHint *bool `json:"destructiveHint,omitempty"`
	// True if repeated calls with the same arguments have no additional effect.
	// Always present; as with `readOnlyHint`, `false` means "not declared
	// idempotent". Only meaningful when `readOnlyHint` is `false`.
	//
	IdempotentHint *bool `json:"idempotentHint,omitempty"`
	// True if the tool interacts with an open world of external entities. **Absent
	// means the server did not declare it**, for which the MCP default is `true`.
	//
	OpenWorldHint *bool `json:"openWorldHint,omitempty"`
}

func (t *ToolAnnotations) GetTitle() *string {
	if t == nil {
		return nil
	}
	return t.Title
}

func (t *ToolAnnotations) GetReadOnlyHint() *bool {
	if t == nil {
		return nil
	}
	return t.ReadOnlyHint
}

func (t *ToolAnnotations) GetDestructiveHint() *bool {
	if t == nil {
		return nil
	}
	return t.DestructiveHint
}

func (t *ToolAnnotations) GetIdempotentHint() *bool {
	if t == nil {
		return nil
	}
	return t.IdempotentHint
}

func (t *ToolAnnotations) GetOpenWorldHint() *bool {
	if t == nil {
		return nil
	}
	return t.OpenWorldHint
}
