// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ToolServerAuthStatus - Authentication status for the calling user.
type ToolServerAuthStatus string

const (
	ToolServerAuthStatusAwaitingAuth ToolServerAuthStatus = "AWAITING_AUTH"
	ToolServerAuthStatusAuthorized   ToolServerAuthStatus = "AUTHORIZED"
)

func (e ToolServerAuthStatus) ToPointer() *ToolServerAuthStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ToolServerAuthStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "AWAITING_AUTH", "AUTHORIZED":
			return true
		}
	}
	return false
}
