// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/gleanwork/api-client-go/internal/utils"
)

type UgcAction struct {
	Create UgcType `json:"create"`
}

func (u UgcAction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UgcAction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UgcAction) GetCreate() UgcType {
	if u == nil {
		return UgcType("")
	}
	return u.Create
}

type UgcActionUnionType string

const (
	UgcActionUnionTypeUgcAction UgcActionUnionType = "UgcAction"
)

// UgcActionUnion - An action to perform on user-generated content. This may be accompanied by `text` on the ChatMessageFragment, which acts as the display name content of the pill.
type UgcActionUnion struct {
	UgcAction *UgcAction `queryParam:"inline" union:"member"`

	Type UgcActionUnionType
}

func CreateUgcActionUnionUgcAction(ugcAction UgcAction) UgcActionUnion {
	typ := UgcActionUnionTypeUgcAction

	return UgcActionUnion{
		UgcAction: &ugcAction,
		Type:      typ,
	}
}

func (u *UgcActionUnion) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = UgcActionUnion{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var ugcAction UgcAction = UgcAction{}
	if err := utils.UnmarshalJSON(data, &ugcAction, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UgcActionUnionTypeUgcAction,
			Value: &ugcAction,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UgcActionUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UgcActionUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(UgcActionUnionType)
	switch best.Type {
	case UgcActionUnionTypeUgcAction:
		u.UgcAction = best.Value.(*UgcAction)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UgcActionUnion", string(data))
}

func (u UgcActionUnion) MarshalJSON() ([]byte, error) {
	if u.UgcAction != nil {
		return utils.MarshalJSON(u.UgcAction, "", true)
	}

	return nil, errors.New("could not marshal union type UgcActionUnion: all fields are null")
}
