workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Glean API:
        inputs:
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs
        output: .speakeasy/glean-merged-spec.yaml
targets:
    glean:
        target: go
        source: Glean API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-go-code-samples
            labelOverride:
                fixedValue: Go (Client)
            blocking: false
        testing:
            enabled: false
